{% set name = "mosdef_cassandra" %}
{% set version = "0.4.0-alpha.2" %}
{% set sha256 = "11d182bfdc3506da73beca2252f022df2ecb2a65dceb52823e11fe00fe7b3765" %}

package:
  name: {{ name|lower }}
  version: "0.4.0"

source:
  url: https://github.com/MaginnGroup/mosdef_cassandra/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win or py<37]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - parmed
    - networkx
    - foyer
    - mbuild
    - cassandra
    - unyt
    - pandas
    - constrainmol
    - gmso >=0.11.1

test:
  imports:
    - mosdef_cassandra

about:
  home: https://github.com/MaginnGroup/mosdef_cassandra
  license: MIT
  license_family: MIT
  license_file: LICENSE.rst
  summary: MoSDeF compatible wrapper for Cassandra Monte Carlo code
  description: |
    mosdef_cassandra is a Python wrapper for the Cassandra Monte Carlo
    code <https://cassandra.nd.edu>. It provides close integration
    with the MoSDeF tools <https://mosdef.org> and provides a user-friendly
    interface to Cassandra.
  doc_url: https://mosdef-cassandra.readthedocs.io/
  dev_url: https://github.com/MaginnGroup/mosdef_cassandra

extra:
  recipe-maintainers:
    - rsdefever
    - emarinri
