{% set name = "mosdef_cassandra" %}
{% set version = "0.3.2" %}
{% set sha256 = "eec5f0fc0e7f5393824ce2dfb1e9fbbd4917dae6bfedf04ca9018031256e0daf" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/MaginnGroup/mosdef_cassandra/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win or py<37]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python >=3.10
    - numpy
    - parmed
    - networkx
    - foyer >=0.11.0
    - mbuild >=0.15.0
    - cassandra >=1.2.2
    - unyt >=2.4
    - pandas >=1.0
    - constrainmol

test:
  imports:
    - mosdef_cassandra

about:
  home: https://github.com/MaginnGroup/mosdef_cassandra
  license: MIT
  license_family: MIT
  license_file: LICENSE.rst
  summary: MoSDeF compatible wrapper for Cassandra Monte Carlo code
  description: |
    mosdef_cassandra is a Python wrapper for the Cassandra Monte Carlo
    code <https://cassandra.nd.edu>. It provides close integration
    with the MoSDeF tools <https://mosdef.org> and provides a user-friendly
    interface to Cassandra.
  doc_url: https://mosdef-cassandra.readthedocs.io/
  dev_url: https://github.com/MaginnGroup/mosdef_cassandra

extra:
  recipe-maintainers:
    - rsdefever
    - emarinri
